name: grafana-9-u
version: 9.0.0
summary: feature rich metrics dashboard and graph editor
base: core20
description: |
  LICENSE: read carrefully the file LICENSE.md 

confinement: strict
grade: stable
architectures:
  - build-on: arm64
  - build-on: amd64

apps:
  grafana:
    command: 'bin/grafana.wrapper'
    plugs: [network-bind, network]
    daemon: simple

  grafana-cli:
    command: 'bin/grafana-cli.wrapper'
    plugs: [network-bind, network]


slots:
  package-assets:
    content: package-assets
    interface: content
    source:
      read:
      - $SNAP/bin/package-assets/grafana-9-u
      
parts:
  snap-wrappers:
    plugin: dump
    source: bin
    organize:
      grafana.wrapper: bin/grafana.wrapper
      grafana-cli.wrapper: bin/grafana-cli.wrapper
      grafana.ini: usr/share/grafana/conf/grafana.ini
      
  
  shscripts:  
    source: conf
    plugin: dump
    organize:
      '*': bin/
  grafana:
    plugin: dump
    source:
         - on amd64: https://dl.grafana.com/enterprise/release/grafana-enterprise_9.0.0_amd64.deb
         - on arm64: https://dl.grafana.com/enterprise/release/grafana-enterprise_9.0.0_arm64.deb
    stage-packages: [libfontconfig1, libfreetype6]

